# Generated by Django 5.0.1 on 2024-03-13 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0004_client_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_User.client')),
                ('vet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_User.vet')),
            ],
        ),
    ]
