# Generated by Django 5.0.1 on 2024-03-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0005_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
