# Generated by Django 5.0.1 on 2024-03-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0006_ratings_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
