# Generated by Django 5.0.1 on 2024-03-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0007_report_comment_report_rating_delete_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
