# Generated by Django 5.0.1 on 2024-03-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0009_remove_report_comment_remove_report_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_history',
            name='healthyWieght',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='hight',
            field=models.IntegerField(default=20, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medical_history',
            name='weight',
            field=models.IntegerField(default=20, max_length=50),
            preserve_default=False,
        ),
    ]
