# Generated by Django 5.0.1 on 2024-03-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0010_medical_history_healthywieght_medical_history_hight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='hight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
