# Generated by Django 5.0.1 on 2024-03-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0011_alter_medical_history_hight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
